version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
      - ./wallet:/wallet
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/bittensor_db
      - API_KEY=${API_KEY}
      - DATURA_API_KEY=${DATURA_API_KEY}
      - CHUTES_API_KEY=${CHUTES_API_KEY}
      - WALLET_PATH=/wallet
      - USE_SEED=${USE_SEED}
      - SEED_PHRASE=${SEED_PHRASE}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK}
      - SUBTENSOR_URL=${SUBTENSOR_URL}
      - DEFAULT_NETUID=${DEFAULT_NETUID}
      - DEFAULT_HOTKEY=${DEFAULT_HOTKEY}
    depends_on:
      - redis
      - db
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./wallet:/wallet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/bittensor_db
      - API_KEY=${API_KEY}
      - DATURA_API_KEY=${DATURA_API_KEY}
      - CHUTES_API_KEY=${CHUTES_API_KEY}
      - WALLET_PATH=/wallet
      - USE_SEED=${USE_SEED}
      - SEED_PHRASE=${SEED_PHRASE}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK}
      - SUBTENSOR_URL=${SUBTENSOR_URL}
      - DEFAULT_NETUID=${DEFAULT_NETUID}
      - DEFAULT_HOTKEY=${DEFAULT_HOTKEY}
    depends_on:
      - redis
      - db
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bittensor_api
    ports:
      - "5433:5432"

volumes:
  redis-data:
  postgres-data: